### ISSUE TITLE
[SUGGESTION] DOI: https://doi.org/10.1016/j.cell.2020.10.049 (Avanzato et al.) Number of case series': {1, 4 sequences) 

### ISSUE THREAD

**Issue by Markman42** [BioWilko/recurrent-sars-cov-2-mutations#13]
A case series will only be included if it fits the inclusion criteria specified in the [original paper](https://doi.org/10.1093/ve/veac050). As well as the inclusion criteria specified within the paper only public sequences with available accessions will be included in this repository via this route.

### Please confirm that each of the below criteria is met by the case series('s) suggested for inclusion:
- [x] Are at least two SARS-CoV-2 genomes from this case series publicly available?
- [x] Is there a time period of at least 28 days between the first genome in the series and the last?
- [x] Is there sufficient public clinical evidence that the patient possessed a suppressed immune system during the time period covered by these genomes?
- [x] Is there sufficient evidence that these genomes are obtained by sampling the same patient?
- [x] Is the first genome within the case series sufficiently high (>= 95% coverage overall, 100% in spike gene) quality? Later genomes can be of lower quality but the "day 0" genome is treated as a baseline.

### Information on case series

| Accession | Day / Date | Coverage % | DOI |
|  MT982403 |20-Apr-2020| full genome for each one below| DOI:https://doi.org/10.1016/j.cell.2020.10.049 
MT982402 |11-May-2020
MT982405 |26-May-2020
MT982406 1|5-Jun-2020|

**Comment by BioWilko** [comment]
Also already present in dataset
