### ISSUE TITLE
[SUGGESTION] DOI: 10.1093/infdis/jiab075 (Tarhini et al.) Number of case series': {2 cases, 7 sequences}

### ISSUE THREAD

**Issue by Markman42** [BioWilko/recurrent-sars-cov-2-mutations#19]
A case series will only be included if it fits the inclusion criteria specified in the [original paper](https://doi.org/10.1093/ve/veac050). As well as the inclusion criteria specified within the paper only public sequences with available accessions will be included in this repository via this route.

### Please confirm that each of the below criteria is met by the case series('s) suggested for inclusion:
- [x] Are at least two SARS-CoV-2 genomes from this case series publicly available?
- [x] Is there a time period of at least 28 days between the first genome in the series and the last?
- [x] Is there sufficient public clinical evidence that the patient possessed a suppressed immune system during the time period covered by these genomes?
- [x] Is there sufficient evidence that these genomes are obtained by sampling the same patient?
- [x] Is the first genome within the case series sufficiently high (>= 95% coverage overall, 100% in spike gene) quality? Later genomes can be of lower quality but the "day 0" genome is treated as a baseline.

### Information on case series

*Note that patient ID should be arbitrary or the same as the source publication, this is purely to distinguish separate case series' within a single submission*

| Patient ID | Accession | Day / Date | Coverage % | DOI |
|1 |EPI_ISL_833192| 6/23/20 |full genome sequencing | DOI: [10.1093/infdis/jiab075](https://doi.org/10.1093/infdis/jiab075) for all sequences|
| 1|  EPI_ISL_833194|7/9/20  |     
| 1 |  EPI_ISL_833191| 7/27/20  |            
| 1| EPI_ISL_833193| 8/18/20 |       
|3| EPI_ISL_833200| 4/30/20 |            
|3| EPI_ISL_833199 | 7/10/20  |       
| 3 | EPI_ISL_833198  | 7/21/20  |           
*Note that patient 2 does not meet criteria

**Comment by BioWilko** [comment]
Already included, thanks for the contribution though!
